### ISSUE TITLE
what is issue today?

### ISSUE THREAD

**Issue by noobie981** [djog/picos_2019#14]

**Comment by noobie981** [comment]
@noobie981 @richelbilderbeek ### ### ### ### ### ### ### ### ### 

> 

> 

> 

> 

> 

> 

> 

> 

> ****__are you dumb or something???

**Comment by rickdecoolegast** [comment]
dome nicolea en hij is cooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooool

**Comment by rickdecoolegast** [comment]
grapje

**Comment by rickdecoolegast** [comment]
hallo

**Comment by richelbilderbeek** [comment]
Ik sluit deze, dit gaat *bijna* nergens over :rainbow:
